version: "3.9"
services:
  db:
    image: postgres:12
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgresdb
      - POSTGRES_DB=books_please_db
